// Mocks generated by Mockito 5.0.17 from annotations
// in currency_app/test/views/currency_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:currency_app/domain/entities/currency.dart' as _i4;
import 'package:currency_app/domain/usecases/load_currencies_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [LoadCurrenciesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadCurrenciesUseCase extends _i1.Mock
    implements _i2.LoadCurrenciesUseCase {
  MockLoadCurrenciesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Currency>> call() =>
      (super.noSuchMethod(Invocation.method(#call, []),
              returnValue: Future<List<_i4.Currency>>.value(<_i4.Currency>[]))
          as _i3.Future<List<_i4.Currency>>);
}
